spring:
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/flower_delivery
    username: admin
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: delivery
        show_sql: true
        format_sql: true
    open-in-view: false  #отключено предупреждение в консоле (сессия Hibernate держится открытой все время обработки HTTP-запроса)